**Please visit https://ProStepSky.github.io/.**

This work © 2024 by "ProStepSky.github.io จัดทำโดย S.U." is licensed under [CC BY-NC-ND 4.0](http://creativecommons.org/licenses/by-nc-nd/4.0/)  
(อ้างอิงแหล่งที่มา ห้ามนำไปใช้เพื่อการค้า และห้ามดัดแปลง)

---

**Note:**

Notebook นี้ "2 - PD - Data Preparation - Test Dataset"

ใช้โค้ดเดียวกันกัน notebook ก่อนหน้า "1 - PD - Data Preparation - Train Dataset"

เพียงแต่เปลี่ยนจาก Train Dataset เป็น Test Dataset และไม่แสดงตารางและกราฟ Weight of Evidence

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Suppress all warnings 
import warnings
warnings.filterwarnings("ignore")

## Import Data

In [3]:
loan_data_backup = pd.read_csv('./data/loan_data_2007_2014.csv')

In [4]:
loan_data = loan_data_backup.copy()

## Explore Data

In [5]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,...,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,...,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,...,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,...,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,...,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [6]:
pd.options.display.max_columns = None
# Set the pandas DataFrame options to display all columns/rows.

In [7]:
loan_data.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
loan_data.tail()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
466280,466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,110000.0,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,773xx,TX,19.85,0.0,Apr-03,2.0,NaN,NaN,18.0,0.0,23208,77.6,36.0,w,12574.00,12574.00,10383.360000,10383.36,5826.00,4557.36,0.0,0.0,0.0,Jan-16,432.64,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,294998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.0,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.0,0.0,0.0,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.0,0.0,0.0,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.0,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.0,0.0,0.0,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.0,0.0,0.0,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

แสดงชื่อของทุก column:

In [9]:
loan_data.columns.values

array(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m'],
      dtype=object)

ตรวจดูชนิดข้อมูล (Dtype):

In [10]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125981 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466264 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(7), object(22)
memory usage: 266.8+ MB

---

## General Preprocessing

ทำทุก continuous variables ให้เป็นตัวเลข:

### Preprocessing few continuous variables

#### ตัวแปร emp_length (จำนวนปีที่ทำงาน)

แสดง categories ของตัวแปร emp_length:

In [11]:
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '1 year', '3 years', '8 years', '9 years',
       '4 years', '5 years', '6 years', '2 years', '7 years', nan],
      dtype=object)

ผลลัพธ์ข้างบนพบ missing values ซึ่งจะไปจัดการในขั้นตอนถัด ๆ ไป

กำจัดตัวอักษรใน emp_length ให้เหลือแค่ตัวเลขเท่านั้น แล้วเอาไปสร้าง column ใหม่ชื่อ emp_length_int:

In [12]:
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('+ years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('n/a',  str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '')

In [13]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])
# Transform the values to numeric.

In [14]:
type(loan_data['emp_length_int'][0])
# Check the datatype of a single element of a column.

numpy.float64

#### ตัวแปร term (จำนวนเดือนที่ผ่อนชำระ: 36, 60 เดือน)

กำจัดตัวอักษรใน term ให้เหลือแค่ตัวเลขเท่านั้น แล้วเอาไปสร้าง column ใหม่ชื่อ term_int:

In [15]:
loan_data['term']

0          36 months
1          60 months
2          36 months
3          36 months
4          60 months
             ...
466280     60 months
466281     60 months
466282     60 months
466283     36 months
466284     36 months
Name: term, Length: 466285, dtype: object

In [16]:
loan_data['term'].describe()

count         466285
unique             2
top        36 months
freq          337953
Name: term, dtype: object

In [17]:
loan_data['term_int'] = loan_data['term'].str.replace(' months', '')

In [18]:
loan_data['term_int'] = pd.to_numeric(loan_data['term_int'])
# Transform the values to numeric.
loan_data['term_int']

0         36
1         60
2         36
3         36
4         60
          ..
466280    60
466281    60
466282    60
466283    36
466284    36
Name: term_int, Length: 466285, dtype: int64

In [19]:
type(loan_data['term_int'][0])
# Check the datatype of a single element of a column.

numpy.int64

#### ตัวแปร earliest_cr_line (เดือนแรกสุดที่สถาบันเปิด credit line ให้ผู้ขอกู้)

In [20]:
loan_data['earliest_cr_line']

0         Jan-85
1         Apr-99
2         Nov-01
3         Feb-96
4         Jan-96
           ...
466280    Apr-03
466281    Jun-97
466282    Dec-01
466283    Feb-03
466284    Feb-00
Name: earliest_cr_line, Length: 466285, dtype: object

แปลงชนิดข้อมูลของตัวแปร earliest_cr_line เป็นชนิด datetime แล้วสร้างเป็นตัวแปรใหม่ชื่อ earliest_cr_line_date:

In [21]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'], format = '%b-%y')

In [22]:
type(loan_data['earliest_cr_line_date'][0])
# Check the datatype of a single element of a column.

pandas._libs.tslibs.timestamps.Timestamp

การหาจำนวนวันที่ผ่านไป โดยปกติจะใช้วันนี้ (today) เป็น reference แต่ dataset นี้เป็น dataset ที่เก่า จึงใช้เดือนธันวาคม 2017 เป็น reference

หาจำนวนเดือนที่ผ่านไปโดยให้ 2017-12-01 เป็น reference:

In [23]:
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['earliest_cr_line_date']) / np.timedelta64(1, 'M')))
# Calculate the difference between two dates in months,
# then turn it to numeric datatype and round it.

In [24]:
loan_data['mths_since_earliest_cr_line'].describe()

count    466256.000000
mean        235.142031
std          92.270010
min        -601.000000
25%         180.000000
50%         221.000000
75%         280.000000
max         576.000000
Name: mths_since_earliest_cr_line, dtype: float64

จากสถิติข้างบนพบว่าทุกอย่างดูปกติดี ยกเว้น min ซึ่งมีค่าติดลบ การเอาเวลาในอนาคตลบด้วยเวลาในอดีตจะต้องได้ค่าเป็นบวก

แสดง datapoints ที่ได้จำนวนเดือนที่ผ่านไป (mths_since_earliest_cr_line) ที่มีค่าติดลบ:

In [25]:
loan_data.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line'] < 0]

       earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
1580             Sep-62            2062-09-01                       -527.0
1770             Sep-68            2068-09-01                       -598.0
2799             Sep-64            2064-09-01                       -551.0
3282             Sep-67            2067-09-01                       -586.0
3359             Feb-65            2065-02-01                       -556.0
...                 ...                   ...                          ...
464003           Jan-68            2068-01-01                       -590.0
464260           Jul-66            2066-07-01                       -572.0
465100           Oct-67            2067-10-01                       -587.0
465500           Sep-67            2067-09-01                       -586.0
465655           Jan-56            2056-01-01                       -449.0

[1169 rows x 3 columns]

พบว่าเกิดจาก datapoints ที่มีข้อมูลเป็นปี 19XX แต่ dataset ได้บันทึกไว้แค่ปีสองตัวท้าย เมื่อใช้ pd.to_datetime จะถูกแปลงเป็น 20XX ซึ่งผิด

แต่การจะแปลงข้อมูลพวกนี้จากปี 20XX เป็น 19XX นั้นเสียเวลาและยุ่งยากมาก

เนื่องจากปี 19XX เป็นระยะเวลาที่ผ่านมาอย่างยาวนานมากแล้ว จึงสามารถแทนค่า mths_since_earliest_cr_line ที่ติดลบพวกนี้ให้เป็นค่าจำนวนเดือนที่สูงที่สุดใน dataset ได้ เพราะว่าค่าจำนวนเดือนที่สูงที่สุดใน dataset เป็นจำนวนเดือนที่สูงอย่างมาก หากแทนค่าด้วยค่านั้นก็ค่อนข้างจะใกล้เคียงกับภาพรวม

โดยทำได้ดังนี้:

In [26]:
loan_data['mths_since_earliest_cr_line'][loan_data['mths_since_earliest_cr_line'] < 0] = loan_data['mths_since_earliest_cr_line'].max()

In [27]:
min(loan_data['mths_since_earliest_cr_line'])
# Calculate and show the minimum value of a column.

72.0

#### ตัวแปร issue_d (เดือนที่ปล่อยกู้)

In [28]:
loan_data['issue_d']

0         Dec-11
1         Dec-11
2         Dec-11
3         Dec-11
4         Dec-11
           ...
466280    Jan-14
466281    Jan-14
466282    Jan-14
466283    Jan-14
466284    Jan-14
Name: issue_d, Length: 466285, dtype: object

แปลงชนิดข้อมูลของตัวแปร issue_d เป็นชนิด datetime แล้วสร้างเป็นตัวแปรใหม่ชื่อ issue_d_date:

In [29]:
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%y')

การหาจำนวนวันที่ผ่านไป โดยปกติจะใช้วันนี้ (today) เป็น reference แต่ dataset นี้เป็น dataset ที่เก่า จึงใช้เดือนธันวาคม 2017 เป็น reference

หาจำนวนเดือนที่ผ่านไปโดยให้ 2017-12-01 เป็น reference:

In [30]:
loan_data['mths_since_issue_d'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['issue_d_date']) / np.timedelta64(1, 'M')))
# Calculate the difference between two dates in months,
# then turn it to numeric datatype and round it.

In [31]:
loan_data['mths_since_issue_d'].describe()

count    466285.000000
mean         50.204806
std          14.190212
min          35.000000
25%          40.000000
50%          46.000000
75%          56.000000
max         124.000000
Name: mths_since_issue_d, dtype: float64

---

### Preprocessing few discrete variables

In [32]:
loan_data.info()
# Display column names, complete (non-missing) cases per column, and datatype per column.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 81 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125981 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466264 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
 75  emp_length_int               445277 non-null  float64
 76  term_int                     466285 non-null  int64
 77  earliest_cr_line_date        466256 non-null  datetime64[ns]
 78  mths_since_earliest_cr_line  466256 non-null  float64
 79  issue_d_date                 466285 non-null  datetime64[ns]
 80  mths_since_issue_d           466285 non-null  float64
dtypes: datetime64[ns](2), float64(49), int64(8), object(22)
memory usage: 288.2+ MB

สร้าง dummy variables สำหรับตัวแปร discrete/categorical ดังต่อไปนี้:

- grade (external credit rating grade)
- sub_grade
- home_ownership (สถานะความเป็นเจ้าของบ้าน)
- verification_status (สถานะการพิสูจน์รายได้)
- loan_status (สถานะการกู้ยืม)
- purpose (วัตถุประสงค์ของการกู้ยืม)
- addr_state (รัฐที่ผู้ขอกู้อาศัยอยู่)
- initial_list_status (สถานะการแบ่งหน่วยลงทุน)

และสร้าง DataFrame ใหม่ชื่อ loan_data_dummies เพื่อเก็บ dummy variables:

In [33]:
loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['sub_grade'], prefix = 'sub_grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['home_ownership'], prefix = 'home_ownership', prefix_sep = ':'),
                     pd.get_dummies(loan_data['verification_status'], prefix = 'verification_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['loan_status'], prefix = 'loan_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['purpose'], prefix = 'purpose', prefix_sep = ':'),
                     pd.get_dummies(loan_data['addr_state'], prefix = 'addr_state', prefix_sep = ':'),
                     pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = ':')]
# Create dummy variables from all 8 original independent variables, and save them into a list.

In [34]:
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)

In [35]:
type(loan_data_dummies)

pandas.core.frame.DataFrame

จากข้างบนพบว่า loan_data_dummies มีชนิดเป็น DataFrame แล้ว

In [36]:
loan_data_dummies

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w
0,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
4,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True
466281,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False
466282,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
466283,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
466284,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False

รวม loan_data_dummies เข้ากับ loan_data ต้นฉบับ:

In [37]:
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)

In [38]:
loan_data.columns.values
# Display all column names.

array(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'emp_length_int', 'term_int', 'earliest_cr_line_date',
       'mths_since_earliest_cr_line', 'issue_d_date',
       'mths_since_issue_d', 'grade:A', 'grade:B', 'grade:C', 'grade:D',
       'grade:E', 'grade:F', 'grade:G', 'sub_grade:A1', 'sub_grade:A2',
       'sub_grade:A3', 'sub_grade:A4', 'sub_grade:A5', 'sub_grade:B1',
       'sub_grade:B2', 'sub_grade:B3', 'sub_grade:B4', 'sub_grade:B5',
       'sub_grade:C1', 'sub_grade:C2', 'sub_grade:C3', 'sub_grade:C4',
       'sub_grade:C5', 'sub_grade:D1', 'sub_grade:D2', 'sub_grade:D3',
       'sub_grade:D4', 'sub_grade:D5', 'sub_grade:E1', 'sub_grade:E2',
       'sub_grade:E3', 'sub_grade:E4', 'sub_grade:E5', 'sub_grade:F1',
       'sub_grade:F2', 'sub_grade:F3', 'sub_grade:F4', 'sub_grade:F5',
       'sub_grade:G1', 'sub_grade:G2', 'sub_grade:G3', 'sub_grade:G4',
       'sub_grade:G5', 'home_ownership:ANY', 'home_ownership:MORTGAGE',
       'home_ownership:NONE', 'home_ownership:OTHER',
       'home_ownership:OWN', 'home_ownership:RENT',
       'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Does not meet the credit policy. Status:Charged Off',
       'loan_status:Does not meet the credit policy. Status:Fully Paid',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Late (16-30 days)', 'loan_status:Late (31-120 days)',
       'purpose:car', 'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:educational', 'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:IA', 'addr_state:ID', 'addr_state:IL', 'addr_state:IN',
       'addr_state:KS', 'addr_state:KY', 'addr_state:LA', 'addr_state:MA',
       'addr_state:MD', 'addr_state:ME', 'addr_state:MI', 'addr_state:MN',
       'addr_state:MO', 'addr_state:MS', 'addr_state:MT', 'addr_state:NC',
       'addr_state:NE', 'addr_state:NH', 'addr_state:NJ', 'addr_state:NM',
       'addr_state:NV', 'addr_state:NY', 'addr_state:OH', 'addr_state:OK',
       'addr_state:OR', 'addr_state:PA', 'addr_state:RI', 'addr_state:SC',
       'addr_state:SD', 'addr_state:TN', 'addr_state:TX', 'addr_state:UT',
       'addr_state:VA', 'addr_state:VT', 'addr_state:WA', 'addr_state:WI',
       'addr_state:WV', 'addr_state:WY', 'initial_list_status:f',
       'initial_list_status:w'], dtype=object)

จากข้างบนพบว่า dummy variables ใหม่ ถูกรวมเข้ากับ loan_data ต้นฉบับแล้ว

### Check for missing values and clean

จัดการ missing values เฉพาะกับตัวแปรที่จะต้องใช้เท่านั้น:

In [39]:
loan_data.isnull()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_int,term_int,earliest_cr_line_date,mths_since_earliest_cr_line,issue_d_date,mths_since_issue_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466281,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466282,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466283,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466284,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

จากข้างบนพบว่า มีบาง datapoints เป็น missing values

นับจำนวน missing values:

In [40]:
pd.options.display.max_rows = None
# Set the pandas DataFrame options to display all rows.
loan_data.isnull().sum()

Unnamed: 0                                                              0
id                                                                      0
member_id                                                               0
loan_amnt                                                               0
funded_amnt                                                             0
funded_amnt_inv                                                         0
term                                                                    0
int_rate                                                                0
installment                                                             0
grade                                                                   0
sub_grade                                                               0
emp_title                                                           27588
emp_length                                                          21008
home_ownership                                                          0
annual_inc                                                              4
verification_status                                                     0
issue_d                                                                 0
loan_status                                                             0
pymnt_plan                                                              0
url                                                                     0
desc                                                               340304
purpose                                                                 0
title                                                                  21
zip_code                                                                0
addr_state                                                              0
dti                                                                     0
delinq_2yrs                                                            29
earliest_cr_line                                                       29
inq_last_6mths                                                         29
mths_since_last_delinq                                             250351
mths_since_last_record                                             403647
open_acc                                                               29
pub_rec                                                                29
revol_bal                                                               0
revol_util                                                            340
total_acc                                                              29
initial_list_status                                                     0
out_prncp                                                               0
out_prncp_inv                                                           0
total_pymnt                                                             0
total_pymnt_inv                                                         0
total_rec_prncp                                                         0
total_rec_int                                                           0
total_rec_late_fee                                                      0
recoveries                                                              0
collection_recovery_fee                                                 0
last_pymnt_d                                                          376
last_pymnt_amnt                                                         0
next_pymnt_d                                                       227214
last_credit_pull_d                                                     42
collections_12_mths_ex_med                                            145
mths_since_last_major_derog                                        367311
policy_code                                                             0
application_type                                                        0
annual_inc_joint                                                   466285
dti_joint                                                          466285
verification_status_joint                                          466285
acc_now_delinq                                                         29
tot_coll_amt                                                        70276
tot_cur_bal                                                         70276
open_acc_6m                                                        466285
open_il_6m                                                         466285
open_il_12m                                                        466285
open_il_24m                                                        466285
mths_since_rcnt_il                                                 466285
total_bal_il                                                       466285
il_util                                                            466285
open_rv_12m                                                        466285
open_rv_24m                                                        466285
max_bal_bc                                                         466285
all_util                                                           466285
total_rev_hi_lim                                                    70276
inq_fi                                                             466285
total_cu_tl                                                        466285
inq_last_12m                                                       466285
emp_length_int                                                      21008
term_int                                                                0
earliest_cr_line_date                                                  29
mths_since_earliest_cr_line                                            29
issue_d_date                                                            0
mths_since_issue_d                                                      0
grade:A                                                                 0
grade:B                                                                 0
grade:C                                                                 0
grade:D                                                                 0
grade:E                                                                 0
grade:F                                                                 0
grade:G                                                                 0
sub_grade:A1                                                            0
sub_grade:A2                                                            0
sub_grade:A3                                                            0
sub_grade:A4                                                            0
sub_grade:A5                                                            0
sub_grade:B1                                                            0
sub_grade:B2                                                            0
sub_grade:B3                                                            0
sub_grade:B4                                                            0
sub_grade:B5                                                            0
sub_grade:C1                                                            0
sub_grade:C2                                                            0
sub_grade:C3                                                            0
sub_grade:C4                                                            0
sub_grade:C5                                                            0
sub_grade:D1                                                            0
sub_grade:D2                                                            0
sub_grade:D3                                                            0
sub_grade:D4                                                            0
sub_grade:D5                                                            0
sub_grade:E1                                                            0
sub_grade:E2                                                            0
sub_grade:E3                                                            0
sub_grade:E4                                                            0
sub_grade:E5                                                            0
sub_grade:F1                                                            0
sub_grade:F2                                                            0
sub_grade:F3                                                            0
sub_grade:F4                                                            0
sub_grade:F5                                                            0
sub_grade:G1                                                            0
sub_grade:G2                                                            0
sub_grade:G3                                                            0
sub_grade:G4                                                            0
sub_grade:G5                                                            0
home_ownership:ANY                                                      0
home_ownership:MORTGAGE                                                 0
home_ownership:NONE                                                     0
home_ownership:OTHER                                                    0
home_ownership:OWN                                                      0
home_ownership:RENT                                                     0
verification_status:Not Verified                                        0
verification_status:Source Verified                                     0
verification_status:Verified                                            0
loan_status:Charged Off                                                 0
loan_status:Current                                                     0
loan_status:Default                                                     0
loan_status:Does not meet the credit policy. Status:Charged Off         0
loan_status:Does not meet the credit policy. Status:Fully Paid          0
loan_status:Fully Paid                                                  0
loan_status:In Grace Period                                             0
loan_status:Late (16-30 days)                                           0
loan_status:Late (31-120 days)                                          0
purpose:car                                                             0
purpose:credit_card                                                     0
purpose:debt_consolidation                                              0
purpose:educational                                                     0
purpose:home_improvement                                                0
purpose:house                                                           0
purpose:major_purchase                                                  0
purpose:medical                                                         0
purpose:moving                                                          0
purpose:other                                                           0
purpose:renewable_energy                                                0
purpose:small_business                                                  0
purpose:vacation                                                        0
purpose:wedding                                                         0
addr_state:AK                                                           0
addr_state:AL                                                           0
addr_state:AR                                                           0
addr_state:AZ                                                           0
addr_state:CA                                                           0
addr_state:CO                                                           0
addr_state:CT                                                           0
addr_state:DC                                                           0
addr_state:DE                                                           0
addr_state:FL                                                           0
addr_state:GA                                                           0
addr_state:HI                                                           0
addr_state:IA                                                           0
addr_state:ID                                                           0
addr_state:IL                                                           0
addr_state:IN                                                           0
addr_state:KS                                                           0
addr_state:KY                                                           0
addr_state:LA                                                           0
addr_state:MA                                                           0
addr_state:MD                                                           0
addr_state:ME                                                           0
addr_state:MI                                                           0
addr_state:MN                                                           0
addr_state:MO                                                           0
addr_state:MS                                                           0
addr_state:MT                                                           0
addr_state:NC                                                           0
addr_state:NE                                                           0
addr_state:NH                                                           0
addr_state:NJ                                                           0
addr_state:NM                                                           0
addr_state:NV                                                           0
addr_state:NY                                                           0
addr_state:OH                                                           0
addr_state:OK                                                           0
addr_state:OR                                                           0
addr_state:PA                                                           0
addr_state:RI                                                           0
addr_state:SC                                                           0
addr_state:SD                                                           0
addr_state:TN                                                           0
addr_state:TX                                                           0
addr_state:UT                                                           0
addr_state:VA                                                           0
addr_state:VT                                                           0
addr_state:WA                                                           0
addr_state:WI                                                           0
addr_state:WV                                                           0
addr_state:WY                                                           0
initial_list_status:f                                                   0
initial_list_status:w                                                   0
dtype: int64

In [41]:
pd.options.display.max_rows = 100
# Set the pandas DataFrame options to display 100 rows.

หากตัวแปร total_rev_hi_lim (วงเงินรวม) มี missing values ให้แทนค่า datapoints เหล่านั้นให้เท่ากับจำนวนเงินที่ให้กู้ยืม (funded_amnt):

In [42]:
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'], inplace=True)

In [43]:
loan_data['total_rev_hi_lim'].isnull().sum()

0

จากข้างบน พบว่าไม่มี missing values ใน total_rev_hi_lim แล้ว

แทนค่า missing values ในตัวแปร annual_inc ด้วยค่าเฉลี่ยของ annual_inc:

In [44]:
loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean(), inplace=True)

ค่า missing values ในตัวแปรดังต่อไปนี้:

- mths_since_earliest_cr_line (จำนวนเดือนที่ผ่านไปนับจากเดือนแรกสุดที่สถาบันเปิด credit line ให้ผู้ขอกู้)
- acc_now_delinq (จำนวนบัญชี ณ ปัจจุบันที่ขาดการชำระเงิน)
- total_acc (จำนวน credit lines ของผู้ขอกู้ ณ ปัจจุบัน)
- pub_rec (จำนวนครั้งที่มีการบันทึกประวัติเสียทางการเงิน)
- open_acc (จำนวนครั้งที่สถาบันเปิด credit lines ให้ผู้ขอกู้)
- inq_last_6mths (จำนวนครั้งที่มีการตรวจสอบข้อมูลเครดิตภายใน 6 เดือนที่ผ่านมา ยกเว้นเพื่อการกู้รถและเพื่อการกู้บ้าน)
- delinq_2yrs (จำนวนครั้งที่จ่ายหนี้ช้ากว่า 30 วัน ภายในสองปีที่ผ่านมา)
- emp_length_int (จำนวนปีที่ทำงาน)

หากไม่มีบันทึกไว้ให้ถือว่าเป็น 0 จึงแทนด้วยค่า 0 ดังนี้:

In [45]:
loan_data['mths_since_earliest_cr_line'].fillna(0, inplace=True)
loan_data['acc_now_delinq'].fillna(0, inplace=True)
loan_data['total_acc'].fillna(0, inplace=True)
loan_data['pub_rec'].fillna(0, inplace=True)
loan_data['open_acc'].fillna(0, inplace=True)
loan_data['inq_last_6mths'].fillna(0, inplace=True)
loan_data['delinq_2yrs'].fillna(0, inplace=True)
loan_data['emp_length_int'].fillna(0, inplace=True)

---

สำหรับตัวแปร `mths_since_last_delinq` (จำนวนเดือนที่ผ่านไปนับจากการขาดการชำระเงินล่าสุด) และ `mths_since_last_record` (จำนวนเดือนที่ผ่านไปนับจากที่มีการบันทึกประวัติเสียทางการเงินล่าสุด) หากแทน missing values ด้วยค่า 0 จะทำให้ความหมายเปลี่ยน เพราะ:

- หากแทนด้วย 0 จะหมายถึง มีการขาดการชำระเงิน หรือ มีการบันทึกประวัติเสียทางการเงิน เกิดขึ้นแล้ว
- หากใช้เป็น missing values จะหมายถึง ยังไม่มีการขาดการชำระเงิน หรือ มีการบันทึกประวัติเสียทางการเงิน เกิดขึ้น

จึงต้องดำเนินการโดย:

- missing values จะรวมให้เป็น 1 dummy variable ของตัวมันเองก่อน
- แล้ว non-missing values ที่เหลือ ค่อยแบ่งเป็น dummy variables อีกทีหนึ่ง

ซึ่งตัวแปร `mths_since_last_delinq` และ `mths_since_last_record` นี้ จะไปดำเนินการในขั้นตอนสร้าง dummy variables ตอนท้าย

---
---
---

# ➡ <font color='dodgerblue'><u>Data Preparation - Test Dataset</u></font> ⬅

### Dependent Variable; Loan Status: Good (Non-default) / Bad (Default)

การสร้าง labels: good และ bad ให้กับตัวแปรตาม "สถานะการกู้ยืม"

#### ตัวแปร loan_status (สถานะการกู้ยืม)

แสดง categories ของตัวแปร loan_status:

In [46]:
loan_data['loan_status'].unique()

array(['Fully Paid', 'Charged Off', 'Current', 'Default',
       'Late (31-120 days)', 'In Grace Period', 'Late (16-30 days)',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

แสดงจำนวนผู้ขอกู้สำหรับแต่ละสถานะการกู้ยืม:

In [47]:
loan_data['loan_status'].value_counts()

loan_status
Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       761
Name: count, dtype: int64

แสดงเป็นสัดส่วนต่อจำนวนการกู้ยืมทั้งหมด:

In [48]:
loan_data['loan_status'].value_counts() / loan_data['loan_status'].count()
# Divide the number of observations for each unique value of a variable by the total number of observations.

loan_status
Current                                                0.480878
Fully Paid                                             0.396193
Charged Off                                            0.091092
Late (31-120 days)                                     0.014798
In Grace Period                                        0.006747
Does not meet the credit policy. Status:Fully Paid     0.004263
Late (16-30 days)                                      0.002612
Default                                                0.001784
Does not meet the credit policy. Status:Charged Off    0.001632
Name: count, dtype: float64

สถานะที่ผิดนัดชำระหนี้ ได้แก่ Charged Off, Default, Does not meet the credit policy. Status:Charged Off, Late (31-120 days)

สร้างตัวแปร good_bad เพื่อเก็บสถานะการผิดนัดชำระหนี้ (0 คือผิดนัดชำระหนี้, 1 คือไม่ผิดนัดชำระหนี้; 0 คือ bad, 1 คือ good):

In [49]:
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off',
                                                                'Default',
                                                                'Does not meet the credit policy. Status:Charged Off',
                                                                'Late (31-120 days)']), 0, 1)

In [50]:
loan_data['good_bad']

0         1
1         0
2         1
3         1
4         1
         ..
466280    1
466281    0
466282    1
466283    1
466284    1
Name: good_bad, Length: 466285, dtype: int32

### Splitting Data

ทำ train/test split ด้วยอัตราส่วน 80:20

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'], test_size = 0.2, random_state = 42)

แสดงมิติของ train/test datasets:

In [53]:
loan_data_inputs_train.shape

(373028, 207)

In [54]:
loan_data_targets_train.shape

(373028,)

In [55]:
loan_data_inputs_test.shape

(93257, 207)

In [56]:
loan_data_targets_test.shape

(93257,)

### Create Working DataFrame

สร้าง working DataFrame คือ df_inputs_prepr กับ df_targets_prepr เพื่อความสะดวกในการทำ data preprocessing กับ train dataset:

In [57]:
##### Train Dataset
#df_inputs_prepr = loan_data_inputs_train
#df_targets_prepr = loan_data_targets_train

##### Test Dataset
df_inputs_prepr = loan_data_inputs_test
df_targets_prepr = loan_data_targets_test

### Data Preparation: An Example ('grade' variable)

สาธิตตัวอย่างการคำนวณกับตัวแปร grade

#### ตัวแปร grade (external credit rating grade)

A คือความน่าเชื่อถือทางเครดิตสูงสุด และ G คือต่ำสุด

แสดง categories ของตัวแปร grade:

In [58]:
df_inputs_prepr['grade'].unique()

array(['C', 'E', 'A', 'D', 'B', 'F', 'G'], dtype=object)

สร้าง DataFrame เพื่อเก็บตัวแปรอิสระคือ grade และตัวแปรตามคือ good_bad (สถานะการผิดนัดชำระหนี้):

In [59]:
df1 = pd.concat([df_inputs_prepr['grade'], df_targets_prepr], axis = 1)
df1.head()

       grade  good_bad
362514     C         1
288564     E         1
213591     C         1
263083     C         1
165001     A         1

นับจำนวนแถวของข้อมูลสำหรับแต่ละ grade:

In [60]:
df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].count()
# as_index = False: Do not turn the names of the values of the criterion as indexes.

  grade  good_bad
0     A     15108
1     B     27199
2     C     25048
3     D     15390
4     E      7145
5     F      2699
6     G       668

เนื่องจาก 0 คือผิดนัดชำระหนี้, 1 คือไม่ผิดนัดชำระหนี้ หากคำนวณค่าเฉลี่ยจะได้เป็นอัตราส่วนของผู้ขอกู้ที่ไม่ผิดนัดชำระหนี้

คำนวณอัตราส่วนของผู้ขอกู้ที่ไม่ผิดนัดชำระหนี้สำหรับแต่ละ grade:

In [61]:
df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].mean()

  grade  good_bad
0     A  0.962338
1     B  0.923085
2     C  0.882905
3     D  0.844314
4     E  0.805178
5     F  0.775472
6     G  0.697605

รวม DataFrames ของจำนวนแถว กับ DataFrame ของ อัตราส่วนของผู้ขอกู้ที่ไม่ผิดนัดชำระหนี้ให้เป็น DataFrame เดียว:

In [62]:
df1 = pd.concat([df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].count(),
                df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].mean()], axis = 1)
# Concatenate two DataFrames along the columns.

In [63]:
df1

  grade  good_bad grade  good_bad
0     A     15108     A  0.962338
1     B     27199     B  0.923085
2     C     25048     C  0.882905
3     D     15390     D  0.844314
4     E      7145     E  0.805178
5     F      2699     F  0.775472
6     G       668     G  0.697605

จากข้างบน ทั้ง 2 columns ที่ชื่อ grade มีชื่อเกรดที่ตรงกัน นั่นคือหลังจากทำการรวม DataFrames แล้วผลลัพธ์ยังคง match กัน

In [64]:
df1 = df1.iloc[:, [0, 1, 3]]
df1

  grade  good_bad  good_bad
0     A     15108  0.962338
1     B     27199  0.923085
2     C     25048  0.882905
3     D     15390  0.844314
4     E      7145  0.805178
5     F      2699  0.775472
6     G       668  0.697605

เปลี่ยนชื่อ columns ให้มีความชัดเจน คือ n_obs (number of observations) และ prop_good (proportion of good borrowers):

In [65]:
df1.columns = [df1.columns.values[0], 'n_obs', 'prop_good']
df1

  grade  n_obs  prop_good
0     A  15108   0.962338
1     B  27199   0.923085
2     C  25048   0.882905
3     D  15390   0.844314
4     E   7145   0.805178
5     F   2699   0.775472
6     G    668   0.697605

คำนวณอัตราส่วนผู้ขอกู้ของละเกรดต่อจำนวนผู้ขอกู้ทั้งหมด:

In [66]:
df1['prop_n_obs'] = df1['n_obs'] / df1['n_obs'].sum()
df1

  grade  n_obs  prop_good  prop_n_obs
0     A  15108   0.962338    0.162004
1     B  27199   0.923085    0.291656
2     C  25048   0.882905    0.268591
3     D  15390   0.844314    0.165028
4     E   7145   0.805178    0.076616
5     F   2699   0.775472    0.028942
6     G    668   0.697605    0.007163

คำนวณจำนวนผู้ขอกู้ที่ผิดนัดชำระหนี้และไม่ผิดนัดชำระหนี้:

In [67]:
df1['n_good'] = df1['prop_good'] * df1['n_obs']
df1['n_bad'] = (1 - df1['prop_good']) * df1['n_obs']
df1

  grade  n_obs  prop_good  prop_n_obs   n_good   n_bad
0     A  15108   0.962338    0.162004  14539.0   569.0
1     B  27199   0.923085    0.291656  25107.0  2092.0
2     C  25048   0.882905    0.268591  22115.0  2933.0
3     D  15390   0.844314    0.165028  12994.0  2396.0
4     E   7145   0.805178    0.076616   5753.0  1392.0
5     F   2699   0.775472    0.028942   2093.0   606.0
6     G    668   0.697605    0.007163    466.0   202.0

คำนวณอัตราส่วนผู้ขอกู้ที่ผิดนัดชำระหนี้ของละเกรดต่อจำนวนผู้ขอกู้ทั้งหมดที่ผิดนัดชำระหนี้ และคำนวณอัตราส่วนผู้ขอกู้ที่ไม่ผิดนัดชำระหนี้ของละเกรดต่อจำนวนผู้ขอกู้ทั้งหมดที่ไม่ผิดนัดชำระหนี้:

In [68]:
df1['prop_n_good'] = df1['n_good'] / df1['n_good'].sum()
df1['prop_n_bad'] = df1['n_bad'] / df1['n_bad'].sum()
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad
0,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839
1,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299
2,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132
4,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605
5,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470
6,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823

คำนวณ WoE (Weight of Evidence) สำหรับตัวแปร grade:

In [69]:
df1['WoE'] = np.log(df1['prop_n_good'] / df1['prop_n_bad'])
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE
0,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839,1.142469
1,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299,0.386785
2,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831,-0.078010
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132,-0.407554
4,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605,-0.679261
5,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470,-0.858767
6,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823,-1.262323

เรียงลำดับ Weight of Evidence จากต่ำไปสูง เพื่อให้กลุ่มผู้ขอกู้ที่มีอัตราการผิดนัดชำระหนี้สูงสุดอยู่ข้างบนสุด:

In [70]:
df1 = df1.sort_values(['WoE'])
df1 = df1.reset_index(drop = True)
# Reset the index of a DataFrame and overwrite it.
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE
0,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823,-1.262323
1,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470,-0.858767
2,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605,-0.679261
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132,-0.407554
4,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831,-0.078010
5,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299,0.386785
6,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839,1.142469

การคำนวณต่อไปนี้ไม่จำเป็นต้องคำนวณก็ได้ แต่สามารถคำนวณเพื่อเอาไว้ (เพื่อให้ทราบว่าจาก grade หนึ่งไปยังอีก grade หนึ่ง มีค่าเพิ่มขึ้นมากน้อยแค่ไหน)

สำหรับ columns ชื่อ prop_good และ WoE; จะทำการคำนวณผลต่างระหว่างค่าที่อยู่ในแถวนั้น ๆ กับค่าที่อยู่ในแถวก่อนหน้า; จากนั้นนำไปเก็บไว้ในตัวแปร diff_prop_good และ diff_WoE:

In [71]:
df1['diff_prop_good'] = df1['prop_good'].diff().abs()
df1['diff_WoE'] = df1['WoE'].diff().abs()
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE
0,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823,-1.262323,NaN,NaN
1,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470,-0.858767,0.077868,0.403556
2,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605,-0.679261,0.029706,0.179506
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132,-0.407554,0.039136,0.271707
4,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831,-0.078010,0.038590,0.329543
5,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299,0.386785,0.040181,0.464796
6,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839,1.142469,0.039252,0.755683

คำนวณ IV (Information Value):

$$\text{Information Value} = \sum_{i=1}^{k}\left[ \left( \%good-\%bad \right) \times \ln \left( \%good \over \%bad \right) \right]$$

In [72]:
df1['IV'] = (df1['prop_n_good'] - df1['prop_n_bad']) * df1['WoE']
df1['IV'] = df1['IV'].sum()
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823,-1.262323,NaN,NaN,0.300551
1,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470,-0.858767,0.077868,0.403556,0.300551
2,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605,-0.679261,0.029706,0.179506,0.300551
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132,-0.407554,0.039136,0.271707,0.300551
4,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831,-0.078010,0.038590,0.329543,0.300551
5,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299,0.386785,0.040181,0.464796,0.300551
6,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839,1.142469,0.039252,0.755683,0.300551

---
### Coarse Classing: Discrete Variables
---

### Preprocessing Discrete Variables: Creating Dummy Variables

#### ตัวแปร grade (external credit rating grade)

A คือความน่าเชื่อถือทางเครดิตสูงสุด และ G คือต่ำสุด

การสร้าง dummy variables:

Weight of Evidence ของตัวแปร grade เพิ่มขึ้นแทบจะสม่ำเสมอจาก grade แย่ที่สุด G ไปยังดีที่สุด A

ดังนั้นจาก pattern นี้ จึงควรเก็บทั้ง 7 categories ของตัวแปร grade แล้วให้แต่ละ grade เป็น dummy variable ของตัวมันเอง

วิเคราะห์ Weight of Evidence ของตัวแปรอิสระต่าง ๆ แล้วทำการรวม categories เข้าด้วยกันเป็น dummy variables:

#### ตัวแปร home_ownership (สถานะความเป็นเจ้าของบ้าน)

การสร้าง dummy variables:

ประเภท `OTHER` กับ `NONE` เป็นผู้ขอกู้ที่มีความเสี่ยงสูงที่สุด แต่ว่ามีสัดส่วนใน dataset (prop_n_obs) ที่ต่ำมาก จึงจะนำไปรวมกับประเภท `RENT` ซึ่งเป็นผู้ขอกู้ที่มีความเสี่ยงสูงอันดับถัดไป

ประเภท `ANY` มีจำนวนผู้ขอกู้ที่น้อยเกินไป (n_obs = 1 คน) ตามทัศนคติ conservative risk management แล้ว ควรสมมติให้สิ่งที่ยังไม่ทราบข้อมูลให้มีความเสี่ยงสูงไว้ก่อน จึงจะนำไปรวมกับประเภท `RENT` เช่นกัน

สาเหตุที่นำ `OTHER`, `NONE`, และ `ANY` ไปรวมกับประเภท `RENT` เพราะว่าพวกมันมีความใกล้เคียงที่สุดคือความเสี่ยงสูงสุด และ `RENT` ก็มีจำนวนผู้ขอกู้มากพอจะให้มันเป็น dummy variable ของตัวมันเอง

ประเภท `OWN` มี Weight of Evidence สูงกว่าประเภท `RENT` ชัดเจน ดังนั้นจึงให้มันเป็น dummy variable ของตัวมันเอง

ประเภท `MORTGAGE` มีสัดส่วน (prop_n_obs) มากถึงครึ่งหนึ่งของ dataset ดังนั้นจึงให้มันเป็น dummy variable ของตัวมันเอง

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [73]:
# 'RENT_OTHER_NONE_ANY' (riskiest group) will be the reference category.
df_inputs_prepr['home_ownership:RENT_OTHER_NONE_ANY'] = \
    sum([df_inputs_prepr['home_ownership:RENT'],
         df_inputs_prepr['home_ownership:OTHER'],
         df_inputs_prepr['home_ownership:NONE'],
         df_inputs_prepr['home_ownership:ANY']])

โค้ดข้างบน สำหรับ dummy variable ใด ๆ ที่มีเพียงแค่ 1 category ไม่จำเป็นต้องสร้าง dummy variable นั้น ๆ ขึ้นมาใหม่ เพราะตัวมันเองก็เป็น dummy variable ของตัวมันเองอยู่แล้ว

#### ตัวแปร addr_state (รัฐที่ผู้ขอกู้อาศัยอยู่)

แสดง categories ของตัวแปร addr_state:

In [74]:
df_inputs_prepr['addr_state'].unique()

array(['CA', 'IN', 'AZ', 'MI', 'PA', 'MO', 'CT', 'IL', 'SC', 'VA', 'NY',
       'FL', 'TX', 'NC', 'NM', 'NJ', 'KY', 'DE', 'OK', 'CO', 'OH', 'GA',
       'LA', 'WA', 'AL', 'TN', 'MD', 'NV', 'MN', 'RI', 'NH', 'MA', 'MS',
       'UT', 'WV', 'HI', 'KS', 'OR', 'WY', 'WI', 'AK', 'DC', 'AR', 'MT',
       'SD', 'VT', 'IA', 'ID', 'ME', 'NE'], dtype=object)

ไม่พบรัฐ North Dakota (ND) ใน dataset จึงเพิ่มคอลัมน์ ND เผื่อมีผู้ขอกู้ที่มาจากรัฐนี้ในอนาคต; จากนั้นกำหนดให้ค่าในคอลัมน์ ND เท่ากับ 0 (เนื่องจากยังไม่เคยมีผู้ขอกู้ที่มาจากรัฐนี้):

In [75]:
if ['addr_state:ND'] in df_inputs_prepr.columns.values:
    # If there is such a dummy variable already, don't do anything.
    pass

else:
    # If there isn't, create it and set all its values to 0 since there aren't any borrowers coming from ND.
    df_inputs_prepr['addr_state:ND'] = 0

การสร้าง dummy variables:

รัฐ NE และ IA มี Weight of Evidence ต่ำอย่างชัดเจนเมื่อเทียบกับรัฐอื่น ๆ

รัฐ ME และ ID มี Weight of Evidence สูงอย่างชัดเจนเมื่อเทียบกับรัฐอื่น ๆ เนื่องจากไม่เคยมีผู้ขอกู้ที่ผิดนัดชำระ

มีความเป็นไปได้สูงมากว่าการที่รัฐ NE, IA, ME, และ ID มีจำนวนผู้ขอกู้ที่น้อยเกินไป เป็นสาเหตุที่ทำให้ WoE ที่มีค่าที่โดดไปมาก และการที่มีจำนวนผู้ขอกู้ที่น้อยเกินไปจึงไม่ควรให้มันเป็น dummy variable ของตัวมันเองเช่นกัน จึงจะรวมรัฐ NE และ IA เข้ากับรัฐที่ WoE ต่ำสุด และจะรวมรัฐ ME และ ID เข้ากับรัฐที่ WoE สูงสุด

การสร้าง dummy variables:

รัฐ NE, IA, NV, FL, HI, AL, และ ND:

- หากจะแยกรัฐ NV เป็น 1 dummy variable และรวมรัฐ FL, HI, และ AL เป็นอีก 1 dummy variable ก็ดูสมเหตุสมผล แต่เนื่องจากรัฐ NV มีจำนวนผู้ขอกู้ที่น้อยเกินไป (prop_n_obs = 0.01) จึงควรรวมรัฐ NV, FL, HI, และ AL เข้าด้วยกันเป็น 1 dummy variable

- และเนื่องจากรัฐ NE และ IA มีจำนวนผู้ขอกู้ที่น้อยเกินไปเช่นกัน

- และรัฐ ND ที่ยังไม่เคยมีผู้ขอกู้มาก่อน (ตามทัศนคติ conservative risk management แล้ว ควรสมมติให้สิ่งที่ยังไม่ทราบข้อมูลให้มีความเสี่ยงสูงไว้ก่อน)

- ดังนั้นจึงรวมรัฐ NE, IA, NV, FL, HI, AL, และ ND เข้าด้วยกันเป็น 1 dummy variable

รัฐ WV, NH, WY, DC, ME, และ ID:

- รัฐ WV, NH, WY, และ DC สามารถรวมเป็น 1 dummy variable ได้เนื่องจากมีจำนวนผู้ขอกู้ที่ค่อนข้างต่ำ

- และเนื่องจากรัฐ ME และ ID มีจำนวนผู้ขอกู้ที่น้อยเกินไปเช่นกัน

- ดังนั้นจึงรวมรัฐ WV, NH, WY, DC, ME, และ ID เข้าด้วยกันเป็น 1 dummy variable

การสร้าง dummy variables:

จากรัฐ NM ถึง CA มี WoE ใกล้เคียงกัน แต่เมื่อดูจำนวนผู้ขอกู้ (n_obs) แล้ว รัฐ NY และ CA มีจำนวนผู้ขอกู้สูงกว่าอย่างเด่นชัด จึงควรให้รัฐ NY และ CA เป็น dummy variables ของตัวมันเอง จะได้เป็น 4 dummy variables:
- กลุ่มรัฐ `NM, VA`
- กลุ่มรัฐ `NY`
- กลุ่มรัฐ `OK, TN, MO, LA, MD, NC`
- กลุ่มรัฐ `CA`

รัฐ `UT, KY, AZ, NJ` มี WoE ใกล้เคียงกัน และไม่มีรัฐไหนที่มีจำนวนผู้ขอกู้สูงกว่ากันอย่างเด่นชัด จึงรวมเข้าด้วยกันเป็น 1 dummy variable

รัฐ `WI, MT` มี WoE ที่ค่อนข้างต่างกัน แต่เนื่องจากพวกมันมีจำนวนผู้ขอกู้ที่ต่ำทั้งคู่ จึงรวมเข้าด้วยกันเป็น 1 dummy variable

รัฐ `TX, IL, CT` มี WoE ใกล้เคียงกัน แต่รัฐ TX มีจำนวนผู้ขอกู้สูงกว่าอย่างเด่นชัด จะได้เป็น 2 dummy variables:
- กลุ่มรัฐ `TX`
- กลุ่มรัฐ `IL, CT`

รัฐ `KS, SC, CO, VT, AK, MS` มีจำนวนผู้ขอกู้ที่ต่ำมาก ซึ่งทำให้ WoE ของรัฐเหล่านี้ไม่ค่อยน่าวางใจได้ จึงรวมเข้าด้วยกันเป็น 1 dummy variable

รัฐ `AR, MI, PA, OH, MN` มี WoE ใกล้เคียงกัน และไม่มีรัฐไหนที่มีจำนวนผู้ขอกู้สูงกว่ากันอย่างเด่นชัด จึงรวมเข้าด้วยกันเป็น 1 dummy variable

รัฐ `RI, MA, DE, SD, IN` มี WoE ใกล้เคียงกัน และไม่มีรัฐไหนที่มีจำนวนผู้ขอกู้สูงกว่ากันอย่างเด่นชัด จึงรวมเข้าด้วยกันเป็น 1 dummy variable

รัฐ `GA, WA, OR` มี WoE ใกล้เคียงกัน และไม่มีรัฐไหนที่มีจำนวนผู้ขอกู้สูงกว่ากันอย่างเด่นชัด จึงรวมเข้าด้วยกันเป็น 1 dummy variable

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [76]:
# 'ND_NE_IA_NV_FL_HI_AL' (riskiest group) will be the reference category.
df_inputs_prepr['addr_state:ND_NE_IA_NV_FL_HI_AL'] = \
    sum([df_inputs_prepr['addr_state:ND'],
         df_inputs_prepr['addr_state:NE'],
         df_inputs_prepr['addr_state:IA'],
         df_inputs_prepr['addr_state:NV'],
         df_inputs_prepr['addr_state:FL'],
         df_inputs_prepr['addr_state:HI'],
         df_inputs_prepr['addr_state:AL']])

df_inputs_prepr['addr_state:NM_VA'] = \
    sum([df_inputs_prepr['addr_state:NM'],
         df_inputs_prepr['addr_state:VA']])

df_inputs_prepr['addr_state:OK_TN_MO_LA_MD_NC'] = \
    sum([df_inputs_prepr['addr_state:OK'],
         df_inputs_prepr['addr_state:TN'],
         df_inputs_prepr['addr_state:MO'],
         df_inputs_prepr['addr_state:LA'],
         df_inputs_prepr['addr_state:MD'],
         df_inputs_prepr['addr_state:NC']])

df_inputs_prepr['addr_state:UT_KY_AZ_NJ'] = \
    sum([df_inputs_prepr['addr_state:UT'],
         df_inputs_prepr['addr_state:KY'],
         df_inputs_prepr['addr_state:AZ'],
         df_inputs_prepr['addr_state:NJ']])

df_inputs_prepr['addr_state:AR_MI_PA_OH_MN'] = \
    sum([df_inputs_prepr['addr_state:AR'],
         df_inputs_prepr['addr_state:MI'],
         df_inputs_prepr['addr_state:PA'],
         df_inputs_prepr['addr_state:OH'],
         df_inputs_prepr['addr_state:MN']])

df_inputs_prepr['addr_state:RI_MA_DE_SD_IN'] = \
    sum([df_inputs_prepr['addr_state:RI'],
         df_inputs_prepr['addr_state:MA'],
         df_inputs_prepr['addr_state:DE'],
         df_inputs_prepr['addr_state:SD'],
         df_inputs_prepr['addr_state:IN']])

df_inputs_prepr['addr_state:GA_WA_OR'] = \
    sum([df_inputs_prepr['addr_state:GA'],
         df_inputs_prepr['addr_state:WA'],
         df_inputs_prepr['addr_state:OR']])

df_inputs_prepr['addr_state:WI_MT'] = \
    sum([df_inputs_prepr['addr_state:WI'],
         df_inputs_prepr['addr_state:MT']])

df_inputs_prepr['addr_state:IL_CT'] = \
    sum([df_inputs_prepr['addr_state:IL'],
         df_inputs_prepr['addr_state:CT']])

df_inputs_prepr['addr_state:KS_SC_CO_VT_AK_MS'] = \
    sum([df_inputs_prepr['addr_state:KS'],
         df_inputs_prepr['addr_state:SC'],
         df_inputs_prepr['addr_state:CO'],
         df_inputs_prepr['addr_state:VT'],
         df_inputs_prepr['addr_state:AK'],
         df_inputs_prepr['addr_state:MS']])

df_inputs_prepr['addr_state:WV_NH_WY_DC_ME_ID'] = \
    sum([df_inputs_prepr['addr_state:WV'],
         df_inputs_prepr['addr_state:NH'],
         df_inputs_prepr['addr_state:WY'],
         df_inputs_prepr['addr_state:DC'],
         df_inputs_prepr['addr_state:ME'],
         df_inputs_prepr['addr_state:ID']])

โค้ดข้างบน สำหรับ dummy variable ใด ๆ ที่มีเพียงแค่ 1 category ไม่จำเป็นต้องสร้าง dummy variable นั้น ๆ ขึ้นมาใหม่ เพราะตัวมันเองก็เป็น dummy variable ของตัวมันเองอยู่แล้ว

#### ตัวแปร verification_status (สถานะการพิสูจน์รายได้)

สถานะการพิสูจน์รายได้: พิสูจน์โดยสถาบันที่ให้กู้แล้ว (Verified), พิสูจน์กับทางที่ทำงานของผู้ขอกู้แล้ว (Source Verified), ยังไม่ได้พิสูจน์ (Not Verified)

การสร้าง dummy variables:

ให้แต่ละ category เป็น dummy variable ของตัวมันเองได้เลย เพราะทุก category มีจำนวนผู้ขอกู้ที่มากพอ และค่า Weight of Evidence ของแต่ละ category ก็เพิ่มขึ้นแทบจะสม่ำเสมอ

In [77]:
# 'Verified' (riskiest group) will be the reference category

#### ตัวแปร purpose (วัตถุประสงค์ของการกู้ยืม)

การสร้าง dummy variables:

small_business, educational, moving, house, other, renewable_energy, medical, wedding, vacation ล้วนมีสัดส่วนจำนวนผู้ขอกู้ (prob_n_obs) ที่ต่ำมากเมื่อเทียบกับทั้ง dataset

- `small_business, educational, moving, house, renewable_energy, wedding` มีลักษณะเหมือนกันคือเป็นการเปลี่ยนแปลงครั้งใหญ่ในชีวิต (major life milestones) จึงรวมให้เป็น 1 dummy variable

- `other, medical, vacation` ไม่ใช่การเปลี่ยนแปลงครั้งใหญ่ในชีวิต จึงรวมให้เป็นอีก 1 dummy variable
    
`debt_consolidtion` มีจำนวนผู้ขอกู้ (n_obs) ที่สูงกว่า categories อื่น ๆ อย่างชัดเจน จึงแยกให้เป็นอีก 1 dummy variable

`home_improvement, major_purchase, car` มี Weight of Evidence ใกล้เคียงกัน จึงรวมให้เป็นอีก 1 dummy variable

`credit_card` มีจำนวนผู้ขอกู้ (n_obs) ที่สูงกว่า categories อื่น ๆ อย่างชัดเจน จึงแยกให้เป็นอีก 1 dummy variable

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [78]:
# 'smb_edu_mov_house_renew_wedd' (riskiest group) will be the reference category.
df_inputs_prepr['purpose:smb_edu_mov_house_renew_wedd'] = \
    sum([df_inputs_prepr['purpose:small_business'],
         df_inputs_prepr['purpose:educational'],
         df_inputs_prepr['purpose:moving'],
         df_inputs_prepr['purpose:house'],
         df_inputs_prepr['purpose:renewable_energy'],
         df_inputs_prepr['purpose:wedding']])

df_inputs_prepr['purpose:oth_med_vacation'] = \
    sum([df_inputs_prepr['purpose:other'],
         df_inputs_prepr['purpose:medical'],
         df_inputs_prepr['purpose:vacation']])

df_inputs_prepr['purpose:homeimpv_majorpurch_car'] = \
    sum([df_inputs_prepr['purpose:home_improvement'],
         df_inputs_prepr['purpose:major_purchase'],
         df_inputs_prepr['purpose:car']])

โค้ดข้างบน สำหรับ dummy variable ใด ๆ ที่มีเพียงแค่ 1 category ไม่จำเป็นต้องสร้าง dummy variable นั้น ๆ ขึ้นมาใหม่ เพราะตัวมันเองก็เป็น dummy variable ของตัวมันเองอยู่แล้ว

#### ตัวแปร initial_list_status (สถานะการแบ่งหน่วยลงทุน)

สถานะการแบ่งหน่วยลงทุน: ผู้ให้กู้หนึ่งคนลงทุนเต็ม (w) หรือ ผู้ให้กู้หลายคนลงทุนแบบเศษหุ้น (f)

Note: สถาบันนี้เป็นตลาดเงินกู้แบบ Peer-to-Peer คือเป็นตัวกลางระหว่างผู้ให้กู้และผู้ขอกู้

การสร้าง dummy variables:

ให้แต่ละ category เป็น dummy variable ของตัวมันเองได้เลย

In [79]:
# 'f' (riskiest group) will be the reference category

---
### Coarse Classing: Continuous Variables
---

### Preprocessing Continuous Variables: Creating Dummy Variables

#### ตัวแปร term_int (จำนวนเดือนที่ผ่อนชำระ: 36, 60 เดือน)

แสดง categories ของตัวแปร term_int:

In [80]:
df_inputs_prepr['term_int'].unique()

array([60, 36], dtype=int64)

จากข้างบนมีเพียง 2 ระดับ จึงไม่จำเป็นต้องทำ fine classing ให้แต่ละระดับเป็น category ได้เลย

จากข้างบนให้แต่ละ category เป็น dummy variable ของตัวมันเองได้เลย

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [81]:
# '60' (riskiest group) will be the reference category.
df_inputs_prepr['term:36'] = np.where((df_inputs_prepr['term_int'] == 36), 1, 0)
df_inputs_prepr['term:60'] = np.where((df_inputs_prepr['term_int'] == 60), 1, 0)

#### ตัวแปร emp_length_int (จำนวนปีที่ทำงาน)

แสดง categories ของตัวแปร emp_length_int:

In [82]:
df_inputs_prepr['emp_length_int'].unique()

array([ 0., 10.,  1.,  2.,  9.,  3.,  6.,  4.,  7.,  8.,  5.])

จากข้างบนมีเพียง 11 ระดับ จึงไม่จำเป็นต้องทำ fine classing ให้แต่ละระดับเป็น category ได้เลย

การสร้าง dummy variables:

แต่ละ category มีจำนวนผู้ขอกู้ (n_obs) ที่มากพอ

สามารถแบ่งกลุ่มตาม Weight of Evidence ที่เปลี่ยนไป ได้เป็น 6 dummy variables ได้แก่ `0`, `1`, `2-4`, `5-6`, `7-9`, `10`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [83]:
# '0' (riskiest group) will be the reference category
df_inputs_prepr['emp_length:0'] = np.where(df_inputs_prepr['emp_length_int'].isin([0]), 1, 0)
df_inputs_prepr['emp_length:1'] = np.where(df_inputs_prepr['emp_length_int'].isin([1]), 1, 0)
df_inputs_prepr['emp_length:2-4'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(2, 5)), 1, 0)
df_inputs_prepr['emp_length:5-6'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(5, 7)), 1, 0)
df_inputs_prepr['emp_length:7-9'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(7, 10)), 1, 0)
df_inputs_prepr['emp_length:10'] = np.where(df_inputs_prepr['emp_length_int'].isin([10]), 1, 0)

#### ตัวแปร mths_since_issue_d (จำนวนเดือนที่ผ่านไปนับจากเดือนที่ปล่อยกู้)

แสดง categories ของตัวแปร mths_since_issue_d:

In [84]:
np.sort(df_inputs_prepr['mths_since_issue_d'].unique())

array([ 35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,
        46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,
        57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,
        68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,
        79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,
        90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.,
       101., 102., 103., 104., 105., 106., 107., 108., 109., 110., 111.,
       112., 113., 114., 115., 116., 117., 118., 119., 120., 121., 122.,
       123., 124.])

จากข้างบนมี 90 ระดับ จึงทำ fine classing ให้เหลือ 50 categories:

In [85]:
df_inputs_prepr['mths_since_issue_d_factor'] = pd.cut(df_inputs_prepr['mths_since_issue_d'], 50)

In [86]:
df_inputs_prepr['mths_since_issue_d_factor']

362514     (38.56, 40.34]
288564     (36.78, 38.56]
213591     (63.48, 65.26]
263083    (34.911, 36.78]
165001     (56.36, 58.14]
               ...
115         (70.6, 72.38]
296284     (36.78, 38.56]
61777      (47.46, 49.24]
91763      (49.24, 51.02]
167512     (56.36, 58.14]
Name: mths_since_issue_d_factor, Length: 93257, dtype: category
Categories (50, interval[float64, right]): [(34.911, 36.78] < (36.78, 38.56] < (38.56, 40.34] < (40.34, 42.12] ... (116.88, 118.66] < (118.66, 120.44] < (120.44, 122.22] < (122.22, 124.0]]

การสร้าง dummy variables:

Categories ที่ 1, 2, 3 มี Weight of Evidence ต่างจาก categories อื่น ๆ มาก จึงให้แต่ละ category เป็น dummy variable ของตัวมันเอง

mths_since_issue_d_factor (จำนวนเดือนที่ผ่านไปนับจากเดือนที่ปล่อยกู้) ต้องเป็นเลขจำนวนเต็มเท่านั้น dummy variables ที่ 1, 2, 3 จึงแบ่งได้เป็น `< 38`, `38-39`, `40-41`

การสร้าง dummy variables:

4 categories แรกมี Weight of Evidence ที่ใกล้เคียงกัน และสูงกว่า categories อื่น ๆ จึงยุบรวมได้เป็น `42-48`

2 categories ถัดมา ยุบรวมได้เป็น `49-52`

7 categories ถัดมา มี Weight of Evidence ที่ใกล้เคียงกัน ยุบรวมได้เป็น `53-64`

categories ถัดมากราฟมีลักษณะขึ้น ๆ ลง ๆ เมื่อตรวจสอบจำนวนผู้ขอกู้ (n_obs) พบว่ามีจำนวนน้อยมากซึ่งเป็นสาเหตุให้กราฟมีลักษณะดังกล่าว เนื่องจาก Weight of Evidence ผันผวนอย่างมาก

เนื่องจากจำนวนผู้ขอกู้มีน้อยมาก จึงสามารถยุบรวม categories ที่เหลือให้เป็น 1 dummy variable ก็ได้ แต่ค่อนข้างจะเป็นช่วงที่กว้างไป ถ้า split ที่ระดับ 84 (คือ 7 ปี) อีกรอบ ก็จะได้ช่วงที่พอเหมาะกว่า ดังนั้น ณ ระดับที่ `65-84` ให้เป็น 1 dummy variable และ ณ ระดับที่ `>84` ให้เป็นอีก 1 dummy variable

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [87]:
# '>84' (riskiest group) will be the reference category
df_inputs_prepr['mths_since_issue_d:<38'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(38)), 1, 0)
df_inputs_prepr['mths_since_issue_d:38-39'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(38, 40)), 1, 0)
df_inputs_prepr['mths_since_issue_d:40-41'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(40, 42)), 1, 0)
df_inputs_prepr['mths_since_issue_d:42-48'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(42, 49)), 1, 0)
df_inputs_prepr['mths_since_issue_d:49-52'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(49, 53)), 1, 0)
df_inputs_prepr['mths_since_issue_d:53-64'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(53, 65)), 1, 0)
df_inputs_prepr['mths_since_issue_d:65-84'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(65, 85)), 1, 0)
df_inputs_prepr['mths_since_issue_d:>84'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(85, int(df_inputs_prepr['mths_since_issue_d'].max()))), 1, 0)

#### ตัวแปร int_rate (อัตราดอกเบี้ย)

ตัวแปร int_rate มีค่าเป็นลักษณะ continuous จึงทำ fine classing ให้เหลือ 50 categories ก่อน:

In [88]:
df_inputs_prepr['int_rate_factor'] = pd.cut(df_inputs_prepr['int_rate'], 50)

การสร้าง dummy variables:

ลักษณะกราฟแทบจะเป็น monotonic คือ ยิ่งอัตราดอกเบี้ยสูง ยิ่งมี Weight of Evidence ต่ำ

10 categories แรก กราฟมีลักษณะขึ้น ๆ ลง ๆ และมี Weight of Evidence ค่อนข้างสูงแต่จำนวนผู้ขอกู้ (n_obs) ไม่ได้มีมาก จึงยุบรวมได้เป็น `<=9.548`

จากนั้น Weight of Evidence ลดลงพอสมควร จึงยุบรวมได้เป็น `9.548-12.025`

จากนั้น Weight of Evidence ลดลงอีกพอสมควร จึงยุบรวมได้เป็น `12.025-15.74`

จากนั้น Weight of Evidence ลดลงอีกพอสมควร จึงยุบรวมได้เป็น `15.74-20.281`

หลังจาก 20.281 เป็นต้นไป Weight of Evidence ไม่ค่อยแตกต่างกันมาก และจำนวนผู้ขอกู้ (n_obs) ค่อยข้างน้อยด้วย จึงยุบรวมได้เป็น `>20.281`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [89]:
# '>20.281' (riskiest group) will be the reference category
df_inputs_prepr['int_rate:<=9.548'] = np.where((df_inputs_prepr['int_rate'] <= 9.548), 1, 0)
df_inputs_prepr['int_rate:9.548-12.025'] = np.where((df_inputs_prepr['int_rate'] > 9.548) & (df_inputs_prepr['int_rate'] <= 12.025), 1, 0)
df_inputs_prepr['int_rate:12.025-15.74'] = np.where((df_inputs_prepr['int_rate'] > 12.025) & (df_inputs_prepr['int_rate'] <= 15.74), 1, 0)
df_inputs_prepr['int_rate:15.74-20.281'] = np.where((df_inputs_prepr['int_rate'] > 15.74) & (df_inputs_prepr['int_rate'] <= 20.281), 1, 0)
df_inputs_prepr['int_rate:>20.281'] = np.where((df_inputs_prepr['int_rate'] > 20.281), 1, 0)

#### ตัวแปร funded_amnt (จำนวนเงินที่ปล่อยกู้)

ตัวแปร funded_amnt มีค่าเป็นลักษณะ continuous จึงทำ fine classing ให้เหลือ 50 categories ก่อน:

In [90]:
df_inputs_prepr['funded_amnt_factor'] = pd.cut(df_inputs_prepr['funded_amnt'], 50)

การสร้าง dummy variables:

กราฟมีลักษณะขึ้น ๆ ลง ๆ คือ Weight of Evidence ผันผวนอย่างมาก และกราฟมีแนวโน้มแทบจะเป็นเส้นแนวราบ

นั่นคือ กราฟไม่มี pattern ที่ชัดเจนและดูเหมือนจะไม่พบความสัมพันธ์ระหว่างตัวแปรอิสระและ Weight of Evidence

ดังนั้น จึงจะไม่ใช้ตัวแปร funded_amnt ในการสร้าง PD model

ดังนั้น จึงไม่จำเป็นต้องสร้าง dummy variables

#### ตัวแปร mths_since_earliest_cr_line (จำนวนเดือนที่ผ่านไปนับจากเดือนแรกสุดที่สถาบันเปิด credit line ให้ผู้ขอกู้)

ตัวแปร mths_since_earliest_cr_line มีค่าเป็นลักษณะ continuous จึงทำ fine classing ให้เหลือ 50 categories ก่อน:

In [91]:
df_inputs_prepr['mths_since_earliest_cr_line_factor'] = pd.cut(df_inputs_prepr['mths_since_earliest_cr_line'], 50)

การสร้าง dummy variables:

ที่ค่า `<140` มี Weight of Evidence ผันผวน จึงยุบรวมเป็น 1 dummy variable

ที่ค่า `141-184` มี Weight of Evidence เพิ่มขึ้นค่อนข้างสม่ำเสมอ จึงยุบรวมเป็น 1 dummy variable

ที่ค่า `185-264` มี Weight of Evidence เพิ่มขึ้นค่อนข้างสม่ำเสมอ จึงยุบรวมเป็น 1 dummy variable

ที่ค่า `265-352` มี Weight of Evidence ใกล้เคียงกัน จึงยุบรวมเป็น 1 dummy variable

ที่ค่า `>352` มี Weight of Evidence ผันผวนอย่างมากและไม่มี pattern ที่ชัดเจน จึงยุบรวมเป็น 1 dummy variable

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [92]:
# '<140' (riskiest group) will be the reference category
df_inputs_prepr['mths_since_earliest_cr_line:<140'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(140)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:141-184'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(141, 185)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:185-264'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(185, 265)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:265-352'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(265, 353)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:>352'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(353, int(df_inputs_prepr['mths_since_earliest_cr_line'].max()))), 1, 0)

#### ตัวแปร delinq_2yrs (จำนวนครั้งที่จ่ายหนี้ช้ากว่า 30 วัน ภายในสองปีที่ผ่านมา)

การสร้าง dummy variables:

ที่ค่าเท่ากับ 0 มี Weight of Evidence สูงมากพิเศษ จึงแยกให้เป็น 1 dummy variable จะได้เป็น `0` 

ที่ค่าเท่ากับ 1-3 มี Weight of Evidence ใกล้เคียงกัน จึงยุบรวมได้เป็น `1-3`

ที่ค่าเท่ากับ 4 เป็นต้นไป มีจำนวนผู้ขอกู้ (n_obs) ต่ำ และมี Weight of Evidence ผันผวนอย่างมากและไม่มี pattern ที่ชัดเจน จึงยุบรวมได้เป็น `>=4`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [93]:
# '>=4' (riskiest group) will be the reference category
df_inputs_prepr['delinq_2yrs:0'] = np.where((df_inputs_prepr['delinq_2yrs'] == 0), 1, 0)
df_inputs_prepr['delinq_2yrs:1-3'] = np.where((df_inputs_prepr['delinq_2yrs'] >= 1) & (df_inputs_prepr['delinq_2yrs'] <= 3), 1, 0)
df_inputs_prepr['delinq_2yrs:>=4'] = np.where((df_inputs_prepr['delinq_2yrs'] >= 9), 1, 0)

#### ตัวแปร inq_last_6mths (จำนวนครั้งที่มีการตรวจสอบข้อมูลเครดิตภายใน 6 เดือนที่ผ่านมา ยกเว้นเพื่อการกู้รถและเพื่อการกู้บ้าน)

การสร้าง dummy variables:

ที่ค่าเท่ากับ 0 ถึง 2 มี Weight of Evidence ลดลงแทบจะสม่ำเสมอและใกล้เคียงกัน
- แต่ที่ค่าเท่ากับ 1 มีจำนวนผู้ขอกู้ (n_obs) ที่สูงมาก จึงแยกให้เป็น 1 dummy variable จะได้เป็น `0` 
- และแยกอีก 1 dummy variable จะได้เป็น `1-2`

ที่ค่าเท่ากับ 3 มีจำนวนผู้ขอกู้ (n_obs) ที่ลดลงจากที่ค่าเท่ากับ 0 ถึง 3 อย่างมาก และที่ค่าเท่ากับ 4 ถึง 6 ก็มีจำนวนผู้ขอกู้ (n_obs) ที่น้อยมาก จึงยุบรวมกันได้เป็น `3-6`

ที่ค่าเท่ากับ 7 เป็นต้นไป มีจำนวนผู้ขอกู้ (n_obs) น้อยมาก จึงยุบรวมกันได้เป็น `>6`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [94]:
# '>6' (riskiest group) will be the reference category
df_inputs_prepr['inq_last_6mths:0'] = np.where((df_inputs_prepr['inq_last_6mths'] == 0), 1, 0)
df_inputs_prepr['inq_last_6mths:1-2'] = np.where((df_inputs_prepr['inq_last_6mths'] >= 1) & (df_inputs_prepr['inq_last_6mths'] <= 2), 1, 0)
df_inputs_prepr['inq_last_6mths:3-6'] = np.where((df_inputs_prepr['inq_last_6mths'] >= 3) & (df_inputs_prepr['inq_last_6mths'] <= 6), 1, 0)
df_inputs_prepr['inq_last_6mths:>6'] = np.where((df_inputs_prepr['inq_last_6mths'] > 6), 1, 0)

#### ตัวแปร open_acc (จำนวนครั้งที่สถาบันเปิด credit lines ให้ผู้ขอกู้)

การสร้าง dummy variables:

Category แรกมี Weight of Evidence ต่ำมากพิเศษ จะได้เป็น `0`

3 categories ถัดมา มีจำนวนผู้ขอกู้ (n_obs) ต่ำ และ Weight of Evidence ผันผวน ยุบรวมได้เป็น `1-3`

9 categories ถัดมา มี Weight of Evidence ใกล้เคียงกันอย่างมาก ยุบรวมได้เป็น `4-12`

10 categories ถัดมา มี Weight of Evidence ใกล้เคียงกันพอควร แต่จะไม่ใกล้เคียงกันอย่างมากเหมือนกลุ่ม 9 categories ก่อนหน้า
- แบ่ง 5 categories แรก ที่มีจำนวนผู้ขอกู้ (n_obs) มากกว่า ยุบรวมได้เป็น `13-17`
- แบ่ง 5 categories หลัง ที่มีจำนวนผู้ขอกู้ (n_obs) น้อยกว่า ยุบรวมได้เป็น `18-22`

8 categories ถัดมา มี Weight of Evidence ที่เริ่มจะผันผวนบ้าง
- แบ่ง 3 categories แรก ที่มีจำนวนผู้ขอกู้ (n_obs) มากกว่า ยุบรวมได้เป็น `23-25`
- แบ่ง 5 categories หลัง ที่มีจำนวนผู้ขอกู้ (n_obs) น้อยกว่า ยุบรวมได้เป็น `26-30`

Categories ที่เหลือ มีจำนวนผู้ขอกู้ (n_obs) ต่ำ และมี Weight of Evidence ผันผวนอย่างมากและไม่มี pattern ที่ชัดเจน จึงยุบรวมได้เป็น `>=31`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [95]:
# '0' (riskiest group) will be the reference category
df_inputs_prepr['open_acc:0'] = np.where((df_inputs_prepr['open_acc'] == 0), 1, 0)
df_inputs_prepr['open_acc:1-3'] = np.where((df_inputs_prepr['open_acc'] >= 1) & (df_inputs_prepr['open_acc'] <= 3), 1, 0)
df_inputs_prepr['open_acc:4-12'] = np.where((df_inputs_prepr['open_acc'] >= 4) & (df_inputs_prepr['open_acc'] <= 12), 1, 0)
df_inputs_prepr['open_acc:13-17'] = np.where((df_inputs_prepr['open_acc'] >= 13) & (df_inputs_prepr['open_acc'] <= 17), 1, 0)
df_inputs_prepr['open_acc:18-22'] = np.where((df_inputs_prepr['open_acc'] >= 18) & (df_inputs_prepr['open_acc'] <= 22), 1, 0)
df_inputs_prepr['open_acc:23-25'] = np.where((df_inputs_prepr['open_acc'] >= 23) & (df_inputs_prepr['open_acc'] <= 25), 1, 0)
df_inputs_prepr['open_acc:26-30'] = np.where((df_inputs_prepr['open_acc'] >= 26) & (df_inputs_prepr['open_acc'] <= 30), 1, 0)
df_inputs_prepr['open_acc:>=31'] = np.where((df_inputs_prepr['open_acc'] >= 31), 1, 0)

#### ตัวแปร pub_rec (จำนวนครั้งที่มีการบันทึกประวัติเสียทางการเงิน)

การสร้าง dummy variables:

ที่ค่าเท่ากับ 0 ถึง 2 มี Weight of Evidence ใกล้เคียงกัน ยุบรวมได้เป็น `0-2`

ที่ค่าเท่ากับ 3 ถึง 4 มี Weight of Evidence ใกล้เคียงกัน และสูงกว่า dummy variable ก่อนหน้า จึงยุบรวมได้เป็น `3-4`

ที่ค่าเท่ากับ 5 เป็นต้นไป มีจำนวนผู้ขอกู้ (n_obs) น้อยมาก จึงยุบรวมได้เป็น `>=5`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [96]:
# '0-2' (riskiest group) will be the reference category
df_inputs_prepr['pub_rec:0-2'] = np.where((df_inputs_prepr['pub_rec'] >= 0) & (df_inputs_prepr['pub_rec'] <= 2), 1, 0)
df_inputs_prepr['pub_rec:3-4'] = np.where((df_inputs_prepr['pub_rec'] >= 3) & (df_inputs_prepr['pub_rec'] <= 4), 1, 0)
df_inputs_prepr['pub_rec:>=5'] = np.where((df_inputs_prepr['pub_rec'] >= 5), 1, 0)

#### ตัวแปร total_acc (จำนวน credit lines ของผู้ขอกู้ ณ ปัจจุบัน)

ตัวแปร total_acc มีค่าเป็นลักษณะ continuous จึงทำ fine classing ให้เหลือ 50 categories ก่อน:

In [97]:
df_inputs_prepr['total_acc_factor'] = pd.cut(df_inputs_prepr['total_acc'], 50)

การสร้าง dummy variables:

ที่ค่าต่ำกว่า 27 มี Weight of Evidence เพิ่มขึ้นเรื่อย ๆ จึงยุบรวมได้เป็น `<=27`

ที่ค่าเท่ากับ 27-51 มี Weight of Evidence ใกล้เคียงกันและมีแนวโน้มเป็นแนวราบ จึงยุบรวมได้เป็น `27-51`

ที่ค่า 51 เป็นต้นไป มี Weight of Evidence ผันผวนอย่างมาก จึงยุบรวมได้เป็น `>51`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [98]:
# '<=27' (riskiest group) will be the reference category
df_inputs_prepr['total_acc:<=27'] = np.where((df_inputs_prepr['total_acc'] <= 27), 1, 0)
df_inputs_prepr['total_acc:27-51'] = np.where((df_inputs_prepr['total_acc'] > 27) & (df_inputs_prepr['total_acc'] <= 51), 1, 0)
df_inputs_prepr['total_acc:>51'] = np.where((df_inputs_prepr['total_acc'] > 51), 1, 0)

#### ตัวแปร acc_now_delinq (จำนวนบัญชี ณ ปัจจุบันที่ขาดการชำระเงิน)

การสร้าง dummy variables:

Category ที่ 1 มีสัดส่วนผู้ขอกู้ (prop_n_obs) สูงถึง 99% ของ dataset จึงให้ category ที่ 1 เป็น dummy variable ของตัวมันเอง จะได้เป็น `0`

Category ที่ 2 ถึง 4 ที่เหลือมีสัดส่วนผู้ขอกู้ (prop_n_obs) รวมกันทั้งหมดไม่ถึง 1% จึงยุบรวมเป็นอีก 1 dummy variable จะได้เป็น `>=1`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [99]:
# '0' (riskiest group) will be the reference category
df_inputs_prepr['acc_now_delinq:0'] = np.where((df_inputs_prepr['acc_now_delinq'] == 0), 1, 0)
df_inputs_prepr['acc_now_delinq:>=1'] = np.where((df_inputs_prepr['acc_now_delinq'] >= 1), 1, 0)

#### ตัวแปร total_rev_hi_lim (วงเงินรวม)

ตัวแปร total_rev_hi_lim มีค่าเป็นลักษณะ continuous จึงทำ fine classing ให้เหลือ 2000 categories ก่อน:

In [100]:
df_inputs_prepr['total_rev_hi_lim_factor'] = pd.cut(df_inputs_prepr['total_rev_hi_lim'], 2000)

การสร้าง dummy variables:

Category ที่ 1 ถึง 8 มี Weight of Evidence เพิ่มขึ้นแทบจะสม่ำเสมอ แต่ category ที่ 1 มีจำนวนผู้ขอกู้ (n_obs) ต่ำกว่า categories ที่ 2 ถึง 8 อย่างพอสมควร

- จึงให้ category ที่ 1 เป็น dummy variables ของตัวมันเอง จะได้เป็น `<=5K`

- แล้วแบ่งช่วง categories ที่ 2 ถึง 8 ให้ห่างกันขั้นละ 10K ได้เป็น `5K-10K`, `10K-20K`, `20K-30K`, `30K-40K`

Categories ที่ 9 ถึง 11 มี Weight of Evidence ใกล้เคียงกัน จึงยุบรวมได้เป็น `40K-55K`

Categories ที่ 12 ถึง 19 มี Weight of Evidence ใกล้เคียงกัน จึงยุบรวมได้เป็น `55K-95K`

Categories ที่ 20 เป็นต้นไปมี Weight of Evidence ผันผวนอย่างมากและแต่ละ category ก็มีจำนวนผู้ขอกู้ (n_obs) น้อยมากด้วย จึงยุบรวมได้เป็น `>95K`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [101]:
# '<=5K' (riskiest group) will be the reference category
df_inputs_prepr['total_rev_hi_lim:<=5K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] <= 5000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:5K-10K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 5000) & (df_inputs_prepr['total_rev_hi_lim'] <= 10000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:10K-20K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 10000) & (df_inputs_prepr['total_rev_hi_lim'] <= 20000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:20K-30K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 20000) & (df_inputs_prepr['total_rev_hi_lim'] <= 30000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:30K-40K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 30000) & (df_inputs_prepr['total_rev_hi_lim'] <= 40000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:40K-55K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 40000) & (df_inputs_prepr['total_rev_hi_lim'] <= 55000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:55K-95K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 55000) & (df_inputs_prepr['total_rev_hi_lim'] <= 95000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:>95K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 95000), 1, 0)

#### ตัวแปร installment (ค่างวด)

ตัวแปร installment มีค่าเป็นลักษณะ continuous จึงทำ fine classing ให้เหลือ 50 categories ก่อน:

In [102]:
df_inputs_prepr['installment_factor'] = pd.cut(df_inputs_prepr['installment'], 50)

การสร้าง dummy variables:

กราฟไม่มี pattern ที่ชัดเจนและดูเหมือนจะไม่พบความสัมพันธ์ระหว่างตัวแปรอิสระและ Weight of Evidence

ดังนั้น จึงจะไม่ใช้ตัวแปร installment ในการสร้าง PD model

ดังนั้น จึงไม่จำเป็นต้องสร้าง dummy variables

#### ตัวแปร annual_inc (รายรับต่อปีของผู้ขอกู้)

ตัวแปร annual_inc มีค่าเป็นลักษณะ continuous จึงทำ fine classing ให้เหลือ 50 categories ก่อน:

In [103]:
df_inputs_prepr['annual_inc_factor'] = pd.cut(df_inputs_prepr['annual_inc'], 50)

ใน category แรก มีจำนวนผู้ขอกู้ (n_obs) 351,904 คน ซึ่งสูงมาก นั่นคือ มากถึง 94% ของ dataset ดังนั้น การทำ fine classing ด้วย 50 categories จึงไม่เพียงพอ

ทำ fine classing ให้เหลือ 100 categories:

In [104]:
df_inputs_prepr['annual_inc_factor'] = pd.cut(df_inputs_prepr['annual_inc'], 100)

จากตารางข้างบน ใน category แรก มีสัดส่วนผู้ขอกู้ (prop_n_obs) ประมาณ 62% ของ dataset ซึ่งยังคงสูงมาก

แต่ก็เป็นปกติของตัวแปร annual_inc (รายรับต่อปีของผู้ขอกู้) ที่ผู้ขอกู้รายรับสูง ๆ มักมีไม่กี่คน

Category ที่ 3 เริ่มต้นที่ประมาณ 144,000 USD จึงถือว่าเป็น threshold ของผู้ขอกู้ที่มีรายได้สูง ซึ่งคิดเป็นประมาณ 5% ของ dataset

ดังนั้น จึงให้มี 1 category สำหรับผู้ขอกู้ที่มีรายรับต่อปีมากกว่า 140K

ทำการสร้างตัวแปร temp สำหรับคัดผู้ขอกู้ที่มีรายรับต่อปีน้อยกว่าหรือเท่ากับ 140K:

In [105]:
df_inputs_prepr_temp = df_inputs_prepr.loc[df_inputs_prepr['annual_inc'] <= 140000, : ]

ทำ fine classing ให้เหลือ 50 categories:

In [106]:
df_inputs_prepr_temp["annual_inc_factor"] = pd.cut(df_inputs_prepr_temp['annual_inc'], 50)

การสร้าง dummy variables:

พบว่า Weight of Evidence เพิ่มขึ้นแทบจะเป็น monotonic จึงแบ่งช่วง categories ให้ห่างกันขั้นละ 10K
- Category แรก ให้เป็น `<20K` เพราะถ้าแบ่งให้ห่างกันขั้นละ 10K จะมีจำนวนผู้ขอกู้ (n_obs) น้อยเกินไป
- 2 categories ท้าย ให้เป็น `100K-120K` และ `120K-140K` เพราะถ้าแบ่งให้ห่างกันขั้นละ 10K จะมีจำนวนผู้ขอกู้ (n_obs) น้อยเกินไป
- Categories ระหว่าง 20K ถึง 100K แบ่งช่วงให้ห่างกันขั้นละ 10K จะได้เป็น `20K-30K`, `30K-40K`, ..., `90K-100K`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [107]:
# '<20K' (riskiest group) will be the reference category
df_inputs_prepr['annual_inc:<20K'] = np.where((df_inputs_prepr['annual_inc'] <= 20000), 1, 0)
df_inputs_prepr['annual_inc:20K-30K'] = np.where((df_inputs_prepr['annual_inc'] > 20000) & (df_inputs_prepr['annual_inc'] <= 30000), 1, 0)
df_inputs_prepr['annual_inc:30K-40K'] = np.where((df_inputs_prepr['annual_inc'] > 30000) & (df_inputs_prepr['annual_inc'] <= 40000), 1, 0)
df_inputs_prepr['annual_inc:40K-50K'] = np.where((df_inputs_prepr['annual_inc'] > 40000) & (df_inputs_prepr['annual_inc'] <= 50000), 1, 0)
df_inputs_prepr['annual_inc:50K-60K'] = np.where((df_inputs_prepr['annual_inc'] > 50000) & (df_inputs_prepr['annual_inc'] <= 60000), 1, 0)
df_inputs_prepr['annual_inc:60K-70K'] = np.where((df_inputs_prepr['annual_inc'] > 60000) & (df_inputs_prepr['annual_inc'] <= 70000), 1, 0)
df_inputs_prepr['annual_inc:70K-80K'] = np.where((df_inputs_prepr['annual_inc'] > 70000) & (df_inputs_prepr['annual_inc'] <= 80000), 1, 0)
df_inputs_prepr['annual_inc:80K-90K'] = np.where((df_inputs_prepr['annual_inc'] > 80000) & (df_inputs_prepr['annual_inc'] <= 90000), 1, 0)
df_inputs_prepr['annual_inc:90K-100K'] = np.where((df_inputs_prepr['annual_inc'] > 90000) & (df_inputs_prepr['annual_inc'] <= 100000), 1, 0)
df_inputs_prepr['annual_inc:100K-120K'] = np.where((df_inputs_prepr['annual_inc'] > 100000) & (df_inputs_prepr['annual_inc'] <= 120000), 1, 0)
df_inputs_prepr['annual_inc:120K-140K'] = np.where((df_inputs_prepr['annual_inc'] > 120000) & (df_inputs_prepr['annual_inc'] <= 140000), 1, 0)
df_inputs_prepr['annual_inc:>140K'] = np.where((df_inputs_prepr['annual_inc'] > 140000), 1, 0)

#### ตัวแปร dti (อัตราส่วนภาระหนี้ต่อเดือน หารรายได้ต่อเดือน)

ตัวแปร dti มีค่าเป็นลักษณะ continuous จึงทำ fine classing ให้เหลือ 100 categories ก่อน:

In [108]:
df_inputs_prepr['dti_factor'] = pd.cut(df_inputs_prepr['dti'], 100)

การสร้าง dummy variables:

ค่าหลังจาก 35 เป็นต้นมีจำนวนผู้ขอกู้ (n_obs) น้อยเกินไป และมี Weight of Evidence ที่ผันผวน จึงยุบรวมให้เหลือเป็น dummy variable เดียว จะได้เป็น `>35`

จากนั้น ทำการพิจารณาค่าที่ 35 หรือน้อยกว่า:

In [109]:
df_inputs_prepr_temp = df_inputs_prepr.loc[df_inputs_prepr['dti'] <= 35, : ]

ทำ fine classing ให้เหลือ 50 categories:

In [110]:
df_inputs_prepr_temp['dti_factor'] = pd.cut(df_inputs_prepr_temp['dti'], 50)

การสร้าง dummy variables:

ทำการตัดแบ่งที่ค่า 1.4 เนื่องจาก WoE สูงขึ้นอย่างชัดเจน จะได้เป็น `<=1.4`

ทำการตัดแบ่งที่ค่า 3.5 เนื่องจาก WoE ต่ำลงที่ (2.8, 3.5] จึงนำไปยุบรวมกับ categories ก่อนหน้า จะได้เป็น `1.4-3.5`

ทำการตัดแบ่งที่ค่า 7.7 เนื่องจาก WoE ใกล้เคียงกันในช่วง 3.5-7.7 จะได้เป็น `3.5-7.7`

หลังจาก 7.7 ไปแล้ว WoE มีแนวโน้มต่ำลงเรื่อย ๆ ด้วยอัตราเร่งพอสมควร จึงตัดที่ค่า 10.5, 16.1, 20.3, 22.4 จะได้เป็น `7.7-10.5`, `10.5-16.1`, `16.1-20.3`, `20.3-22.4`

หลังจาก 22.4 ไปแล้ว WoE มีแนวโน้มต่ำลงเรื่อย ๆ ด้วยอัตราเร่งที่น้อยแล้ว ประกอบกับจำนวนผู้ขอกู้เริ่มลดลงเรื่อย ๆ จนถึงสุดขอบกราฟที่ 35 จึงยุบรวมได้เป็น `22.4-35`

(จากที่ได้กล่าวไว้กับกราฟแบบเต็มก่อนหน้านี้:) ค่าหลังจาก 35 เป็นต้นมีจำนวนผู้ขอกู้ (n_obs) น้อยเกินไป และมี Weight of Evidence ที่ผันผวน จึงยุบรวมให้เหลือเป็น dummy variable เดียว จะได้เป็น `>35`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [111]:
# '>35' (riskiest group) will be the reference category
df_inputs_prepr['dti:<=1.4'] = np.where((df_inputs_prepr['dti'] <= 1.4), 1, 0)
df_inputs_prepr['dti:1.4-3.5'] = np.where((df_inputs_prepr['dti'] > 1.4) & (df_inputs_prepr['dti'] <= 3.5), 1, 0)
df_inputs_prepr['dti:3.5-7.7'] = np.where((df_inputs_prepr['dti'] > 3.5) & (df_inputs_prepr['dti'] <= 7.7), 1, 0)
df_inputs_prepr['dti:7.7-10.5'] = np.where((df_inputs_prepr['dti'] > 7.7) & (df_inputs_prepr['dti'] <= 10.5), 1, 0)
df_inputs_prepr['dti:10.5-16.1'] = np.where((df_inputs_prepr['dti'] > 10.5) & (df_inputs_prepr['dti'] <= 16.1), 1, 0)
df_inputs_prepr['dti:16.1-20.3'] = np.where((df_inputs_prepr['dti'] > 16.1) & (df_inputs_prepr['dti'] <= 20.3), 1, 0)
df_inputs_prepr['dti:20.3-22.4'] = np.where((df_inputs_prepr['dti'] > 20.3) & (df_inputs_prepr['dti'] <= 22.4), 1, 0)
df_inputs_prepr['dti:22.4-35'] = np.where((df_inputs_prepr['dti'] > 22.4) & (df_inputs_prepr['dti'] <= 35), 1, 0)
df_inputs_prepr['dti:>35'] = np.where((df_inputs_prepr['dti'] > 35), 1, 0)

---

จากขั้นตอน pre-processing ในตอนแรก ได้กล่าวไว้ว่า:

สำหรับตัวแปร `mths_since_last_delinq` (จำนวนเดือนที่ผ่านไปนับจากการขาดการชำระเงินล่าสุด) และ `mths_since_last_record` (จำนวนเดือนที่ผ่านไปนับจากที่มีการบันทึกประวัติเสียทางการเงินล่าสุด) หากแทน missing values ด้วยค่า 0 จะทำให้ความหมายเปลี่ยน เพราะ:

- หากแทนด้วย 0 จะหมายถึง มีการขาดการชำระเงิน หรือ มีการบันทึกประวัติเสียทางการเงิน เกิดขึ้นแล้ว
- หากใช้เป็น missing values จะหมายถึง ยังไม่มีการขาดการชำระเงิน หรือ มีการบันทึกประวัติเสียทางการเงิน เกิดขึ้น

จึงต้องดำเนินการโดย:

- missing values จะรวมให้เป็น 1 dummy variable ของตัวมันเองก่อน
- แล้ว non-missing values ที่เหลือ ค่อยแบ่งเป็น dummy variables อีกทีหนึ่ง

และขณะนี้ จะได้ดำเนินการกับตัวแปร `mths_since_last_delinq` และ `mths_since_last_record` ในลำดับถัดไป:

---

#### ตัวแปร mths_since_last_delinq (จำนวนเดือนที่ผ่านไปนับจากการขาดการชำระเงินล่าสุด)

เลือกดำเนินการกับ non-missing values ก่อน:

In [112]:
df_inputs_prepr_temp = df_inputs_prepr[pd.notnull(df_inputs_prepr['mths_since_last_delinq'])]

ทำ fine classing ให้เหลือ 50 categories ก่อน:

In [113]:
df_inputs_prepr_temp['mths_since_last_delinq_factor'] = pd.cut(df_inputs_prepr_temp['mths_since_last_delinq'], 50)

การสร้าง dummy variables:

Category แรก มี Weight of Evidence ต่ำกว่าเมื่อเทียบกับ categories ถัด ๆ ไป จะได้เป็นค่าระหว่าง `0-3`

7 categories ถัดมา มี Weight of Evidence ใกล้เคียงกัน จะยุบรวมได้เป็น `4-30`

7 categories ถัดมาอีก มี Weight of Evidence ใกล้เคียงกัน จะยุบรวมได้เป็น `31-56`

Categories ที่ค่าระหว่าง 57 ถึง 82 มี Weight of Evidence ใกล้เคียงกัน แต่ categories หลังจากค่า 82 ไปแล้ว มีจำนวนผู้ขอกู้ (n_obs) น้อยมาก จึงยุบรวม categories หลังจากค่า 82 จากนั้นนำไปรวมกับ categories ที่ค่าระหว่าง 57 ถึง 82 ก่อนหน้า จะได้เป็น `>=57`

Missing values ให้รวมเป็น 1 dummy variable ของตัวมันเอง จะได้เป็น `Missing`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [114]:
# '0-3' (riskiest group) will be the reference category
df_inputs_prepr['mths_since_last_delinq:Missing'] = np.where((df_inputs_prepr['mths_since_last_delinq'].isnull()), 1, 0)
df_inputs_prepr['mths_since_last_delinq:0-3'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 0) & (df_inputs_prepr['mths_since_last_delinq'] <= 3), 1, 0)
df_inputs_prepr['mths_since_last_delinq:4-30'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 4) & (df_inputs_prepr['mths_since_last_delinq'] <= 30), 1, 0)
df_inputs_prepr['mths_since_last_delinq:31-56'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 31) & (df_inputs_prepr['mths_since_last_delinq'] <= 56), 1, 0)
df_inputs_prepr['mths_since_last_delinq:>=57'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 57), 1, 0)

#### ตัวแปร mths_since_last_record (จำนวนเดือนที่ผ่านไปนับจากที่มีการบันทึกประวัติเสียทางการเงินล่าสุด)

เลือกดำเนินการกับ non-missing values ก่อน:

In [115]:
df_inputs_prepr_temp = df_inputs_prepr[pd.notnull(df_inputs_prepr['mths_since_last_record'])]

ทำ fine classing ให้เหลือ 50 categories ก่อน:

In [116]:
df_inputs_prepr_temp['mths_since_last_record_factor'] = pd.cut(df_inputs_prepr_temp['mths_since_last_record'], 50)

การสร้าง dummy variables:

Category แรก มี Weight of Evidence ต่ำเป็นพิเศษ จะได้เป็น `0-2`

8 categories ถัดมา Weight of Evidence มีแนวโน้มสูงขึ้น ยุบรวมได้เป็น `3-20`

4 categories ถัดมา Weight of Evidence มีค่า drop ลงและใกล้เคียงกัน ยุบรวมได้เป็น `21-31`

ถัดมา เป็นค่าระหว่าง 32-80 พบ Weight of Evidence มีแนวโน้มค่อย ๆ ลดลงช้า ๆ ยุบรวมได้เป็น `32-80`

3 categories ถัดมา Weight of Evidence มีแนวโน้มลดลงด้วยอัตราเร่งที่มากขึ้น ยุบรวมได้เป็น `81-86`

Categories ที่เหลือ พบ Weight of Evidence มีแนวโน้มค่อย ๆ กลับมาเพิ่มขึ้นช้า ๆ จึงยุบรวมได้เป็น `>86`

Missing values ให้รวมเป็น 1 dummy variable ของตัวมันเอง จะได้เป็น `Missing`

ทำการสร้าง dummy variables ดังที่กล่าวไปได้ดังนี้:

In [117]:
# '0-2' (riskiest group) will be the reference category
df_inputs_prepr['mths_since_last_record:Missing'] = np.where((df_inputs_prepr['mths_since_last_record'].isnull()), 1, 0)
df_inputs_prepr['mths_since_last_record:0-2'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 0) & (df_inputs_prepr['mths_since_last_record'] <= 2), 1, 0)
df_inputs_prepr['mths_since_last_record:3-20'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 3) & (df_inputs_prepr['mths_since_last_record'] <= 20), 1, 0)
df_inputs_prepr['mths_since_last_record:21-31'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 21) & (df_inputs_prepr['mths_since_last_record'] <= 31), 1, 0)
df_inputs_prepr['mths_since_last_record:32-80'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 32) & (df_inputs_prepr['mths_since_last_record'] <= 80), 1, 0)
df_inputs_prepr['mths_since_last_record:81-86'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 81) & (df_inputs_prepr['mths_since_last_record'] <= 86), 1, 0)
df_inputs_prepr['mths_since_last_record:>86'] = np.where((df_inputs_prepr['mths_since_last_record'] > 86), 1, 0)

### Export the Train Dataset

In [118]:
##### Train Dataset
#loan_data_inputs_train = df_inputs_prepr

##### Test Dataset
loan_data_inputs_test = df_inputs_prepr

In [119]:
##### Train Dataset
#loan_data_inputs_train.to_csv('./data/loan_data_inputs_train.csv')
#loan_data_targets_train.to_csv('./data/loan_data_targets_train.csv')

##### Test Dataset
loan_data_inputs_test.to_csv('./data/loan_data_inputs_test.csv')
loan_data_targets_test.to_csv('./data/loan_data_targets_test.csv')

---

# End of notebook.

---